services:
  db:
    image: postgres:latest
    container_name: my_db_tarawut
    ports:
      - "65432:5432"    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    image: prawee/strapi
    container_name: my_app_tarawut002 
    ports:
      - "8080:1337"
    environment:
      DATABASE_CLIENT : ${DATABASE_CLIENT}
      DATABASE_NAME : ${DATABASE_NAME}
      DATABASE_HOST : ${DATABASE_HOST}
      DATABASE_PORT : ${DATABASE_PORT}
      DATABASE_USERNAME : ${DATABASE_USERNAME}
      DATABASE_PASSWORD : ${DATABASE_PASSWORD}
      DATABASE_SSL : false
